### ISSUE TITLE
ExternalError for Add 10 question

### ISSUE THREAD

**Issue by caitlind** [uccser/codewof#19]
When the tests are run for the "Add 10" question they fail with the error message:

ExternalError: TypeError: t.test_input_list is undefined on line 1

This seems to only happen when the code includes input(), if it just prints 34 then the first test passes, and when there is no code written it gives the expected "No Python code provided." output.

![Screenshot from 2019-06-06 11-04-47](https://user-images.githubusercontent.com/18223869/58996104-f02dc680-884a-11e9-9927-2447130aceeb.png)

**Comment by JackMorganNZ** [comment]
Fixed in `1.0.0`.
