### ISSUE TITLE
Dev deploy always exceeds time limit when deploying to GAE

### ISSUE THREAD

**Issue by courtneycb** [uccser/codewof#206]
`UNKNOWN: Error Response: [4] DEADLINE_EXCEEDED`

Within this job the project is built, started, and updated, then the command is given for GAE to build the project itself. No actions are taken on the original build so potentially those steps could be removed?

Potential solution - increase the timeout with gcloud config command.

![image](https://user-images.githubusercontent.com/16066822/79291214-2683aa00-7f22-11ea-8159-17b962b744c5.png)

**Comment by eAlasdair** [comment]
Time limit was increased and no further problems have been found, so closing for now
