### ISSUE TITLE
Production cron job url not exempt from secure redirects

### ISSUE THREAD

**Issue by eAlasdair** [uccser/codewof#249]
The cron job sends an HTTP GET request to /tasks/backdate/ minutely (telling the server to backdate 15 users) but receives a 301 code (redirect) in response. It must be 2XX to be successful.

The issue is most likely that the setting that exempts that url from https isn't working on production

**Comment by JackMorganNZ** [comment]
Fixed in 1f85e8a23521e308e5455aae6b1e5ec43a6a48d5 as now running as cron job on server.
