### ISSUE TITLE
Redundancy loading questions in dev scripts

### ISSUE THREAD

**Issue by eAlasdair** [uccser/codewof#260]
The dev update command loads questions and style errors
The dev sampledata command loads questions and style errors
The deployment script loads questions and style errors

Since it's impossible to view any questions without one of the latter two scripts, loading questions in the former can be removed.

Since it _is_ possible to view the style checker without logging in, and since the sampledata command first wipes the database, the style script is necessary everywhere.

We should check if this reasoning is accurate and act appropriately, especially since the questions loader is very computationally slow.

**Comment by eAlasdair** [comment]
It appears the update command isn't used in any deployment environment so the impact of this issue is very low

**Comment by JackMorganNZ** [comment]
Correct, `update` is aimed to get a local production system up and running, while our development tasks each have specific tasks. Do you think this issue should remain open?

**Comment by eAlasdair** [comment]
Even locally it's impossible to view any questions with just the update command alone - as an account is required to log in. The issue exists but it's importance is negligible so I'll close it
