### ISSUE TITLE
New question list layout

### ISSUE THREAD

**Issue by lucyturn3r** [uccser/codewof#27]
Change the layout of the list of questions to be similar to that shown in the image attached. 

- They could be ordered alphabetically, and would rearrange themselves to fit to the screen size. 

- Unsure of what the best colours would be to accommodate for a range of colour-blindness.

- Questions that have been completed would be filled with the colour of that question type, and questions that have not been completed would have the colour of the question type as their border.

![question layout](https://user-images.githubusercontent.com/27177303/62840269-d8137100-bceb-11e9-843d-995088682a2e.jpg)

**Comment by lucyturn3r** [comment]
Potential colour palette:
#D03A71 (pink)
#639ACA (blue)
#FFC107 (yellow)
#6AAD6F (green)

**Comment by lucyturn3r** [comment]
New better idea!!! (from Jack)

The dashed background in the new picture attached represents a lighter/less opaque version of the colour used for the outlines. 

![IMG_20190812_144358](https://user-images.githubusercontent.com/27177303/62843695-e83d4780-bd0f-11e9-9183-8f5b894e4139.jpg)

**Comment by JackMorganNZ** [comment]
Implemented in `1.0.0`.
