### ISSUE TITLE
Fix reCAPTCHA keys

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/codewof#39]

**Comment by eAlasdair** [comment]
This might be related, from the sign up page

![image](https://user-images.githubusercontent.com/25916475/62989413-ed2f0200-be9b-11e9-96dd-91dec9fee1a4.png)

**Comment by JackMorganNZ** [comment]
Fixed in a01c12f20eeabaa787eb13f2b360803b50e89f02
